# https://book.getfoundry.sh/reference/config/overview

[profile.default]

libs = ["lib"]

optimizer = true
optimizer_runs = 1

remappings = [
	"@ens/=lib/ens-contracts/contracts/"
]

# forge i foundry-rs/forge-std
# forge i ensdomains/ens-contracts
